sudo: true
dist: trusty
cache: false
env:
  global:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_982ed3ed7da0_key -iv $encrypted_982ed3ed7da0_iv
  -in assets/server.key.enc -out assets/server.key -d

- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
# The URL sfdx image now gives OS and version in the folder name, which would break the 
# build on version changes, so we create an 'sfdx' folder
# and we wget and unpack into that
# then install. (4 lines of comments to explain 3 lines of code)
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
# done unpacking the sfdx cli, on to other stuff like adding to path and using it
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update

- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p
